name: Build EXE on Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build application
        run: pyinstaller PenningMaatje.py --onefile --windowed  --clean --noconfirm -i src\logo.ico --add-data resources:resources

      - name: Upload EXE
        uses: actions/upload-artifact@v5
        with:
          name: PenningMaatje
          path: dist/*.exe
